# Before running this, make sure in mtst.py file in def load_data(self, lang):, it always load from en_* df (for train and dev, not for test), I mean lang is always 'en' in this case for train and dev but for test it will be individual langs.

##########################################################################################
# python mtst.py --task pos_to_neg --lang bn --src_lang_code bn_IN --trg_lang_code bn_IN --methodology parallel --src POSITIVE_ben_Beng --trg NEGATIVE_ben_Beng --test_src POSITIVE --test_trg NEGATIVE --test_print_src POSITIVE --output_file ../output/pos_to_neg-bn-en_tr_ip-parallel.csv
# python mtst.py --task neg_to_pos --lang bn --src_lang_code bn_IN --trg_lang_code bn_IN --methodology parallel --src NEGATIVE_ben_Beng --trg POSITIVE_ben_Beng --test_src NEGATIVE --test_trg POSITIVE --test_print_src NEGATIVE --output_file ../output/neg_to_pos-bn-en_tr_ip-parallel.csv
######################################################################################
python mtst.py --task pos_to_neg --lang hi --src_lang_code hi_IN --trg_lang_code hi_IN --methodology parallel --src POSITIVE_hin_Deva --trg NEGATIVE_hin_Deva --test_src POSITIVE --test_trg NEGATIVE --test_print_src POSITIVE --output_file ../output/pos_to_neg-hi-en_tr_ip-parallel.csv
python mtst.py --task neg_to_pos --lang hi --src_lang_code hi_IN --trg_lang_code hi_IN --methodology parallel --src NEGATIVE_hin_Deva --trg POSITIVE_hin_Deva --test_src NEGATIVE --test_trg POSITIVE --test_print_src NEGATIVE --output_file ../output/neg_to_pos-hi-en_tr_ip-parallel.csv
######################################################################################
python mtst.py --task pos_to_neg --lang mr --batch_size 16 --src_lang_code mr_IN --trg_lang_code mr_IN --methodology parallel --src POSITIVE_mar_Deva --trg NEGATIVE_mar_Deva --test_src POSITIVE --test_trg NEGATIVE --test_print_src POSITIVE --output_file ../output/pos_to_neg-mr-en_tr_ip-parallel.csv
python mtst.py --task neg_to_pos --lang mr --batch_size 16 --src_lang_code mr_IN --trg_lang_code mr_IN --methodology parallel --src NEGATIVE_mar_Deva --trg POSITIVE_mar_Deva --test_src NEGATIVE --test_trg POSITIVE --test_print_src NEGATIVE --output_file ../output/neg_to_pos-mr-en_tr_ip-parallel.csv
# ######################################################################################
python mtst.py --task pos_to_neg --lang ml --src_lang_code ml_IN --trg_lang_code ml_IN --methodology parallel --src POSITIVE_mal_Mlym --trg NEGATIVE_mal_Mlym --test_src POSITIVE --test_trg NEGATIVE --test_print_src POSITIVE --output_file ../output/pos_to_neg-ml-en_tr_ip-parallel.csv
python mtst.py --task neg_to_pos --lang ml --src_lang_code ml_IN --trg_lang_code ml_IN --methodology parallel --src NEGATIVE_mal_Mlym --trg POSITIVE_mal_Mlym --test_src NEGATIVE --test_trg POSITIVE --test_print_src NEGATIVE --output_file ../output/neg_to_pos-ml-en_tr_ip-parallel.csv
# ######################################################################################
python mtst.py --task pos_to_neg --lang ur --src_lang_code ur_PK --trg_lang_code ur_PK --methodology parallel --src POSITIVE_urd_Arab --trg NEGATIVE_urd_Arab --test_src POSITIVE --test_trg NEGATIVE --test_print_src POSITIVE --output_file ../output/pos_to_neg-ur-en_tr_ip-parallel.csv
python mtst.py --task neg_to_pos --lang ur --src_lang_code ur_PK --trg_lang_code ur_PK --methodology parallel --src NEGATIVE_urd_Arab --trg POSITIVE_urd_Arab --test_src NEGATIVE --test_trg POSITIVE --test_print_src NEGATIVE --output_file ../output/neg_to_pos-ur-en_tr_ip-parallel.csv
# ######################################################################################
python mtst.py --task pos_to_neg --lang mag --src_lang_code hi_IN --trg_lang_code hi_IN --methodology parallel --src POSITIVE_mag_Deva --trg NEGATIVE_mag_Deva --test_src POSITIVE --test_trg NEGATIVE --test_print_src POSITIVE --output_file ../output/pos_to_neg-mag-en_tr_ip-parallel.csv
python mtst.py --task neg_to_pos --lang mag --src_lang_code hi_IN --trg_lang_code hi_IN --methodology parallel --src NEGATIVE_mag_Deva --trg POSITIVE_mag_Deva --test_src NEGATIVE --test_trg POSITIVE --test_print_src NEGATIVE --output_file ../output/neg_to_pos-mag-en_tr_ip-parallel.csv
# ######################################################################################
python mtst.py --task pos_to_neg --lang pa --src_lang_code hi_IN --trg_lang_code hi_IN --methodology parallel --src POSITIVE_pan_Guru --trg NEGATIVE_pan_Guru --test_src POSITIVE --test_trg NEGATIVE --test_print_src POSITIVE --output_file ../output/pos_to_neg-pa-en_tr_ip-parallel.csv
python mtst.py --task neg_to_pos --lang pa --src_lang_code hi_IN --trg_lang_code hi_IN --methodology parallel --src NEGATIVE_pan_Guru --trg POSITIVE_pan_Guru --test_src NEGATIVE --test_trg POSITIVE --test_print_src NEGATIVE --output_file ../output/neg_to_pos-pa-en_tr_ip-parallel.csv
# ######################################################################################
python mtst.py --task pos_to_neg --lang or --src_lang_code hi_IN --trg_lang_code hi_IN --methodology parallel --src POSITIVE_ory_Orya --trg NEGATIVE_ory_Orya --test_src POSITIVE --test_trg NEGATIVE --test_print_src POSITIVE --output_file ../output/pos_to_neg-or-en_tr_ip-parallel.csv
python mtst.py --task neg_to_pos --lang or --src_lang_code hi_IN --trg_lang_code hi_IN --methodology parallel --src NEGATIVE_ory_Orya --trg POSITIVE_ory_Orya --test_src NEGATIVE --test_trg POSITIVE --test_print_src NEGATIVE --output_file ../output/neg_to_pos-or-en_tr_ip-parallel.csv
# ######################################################################################
python mtst.py --task pos_to_neg --lang te --src_lang_code te_IN --trg_lang_code te_IN --methodology parallel --src POSITIVE_tel_Telu --trg NEGATIVE_tel_Telu --test_src POSITIVE --test_trg NEGATIVE --test_print_src POSITIVE --output_file ../output/pos_to_neg-or-en_tr_ip-parallel.csv
python mtst.py --task neg_to_pos --lang te --src_lang_code te_IN --trg_lang_code te_IN --methodology parallel --src NEGATIVE_tel_Telu --trg POSITIVE_tel_Telu --test_src NEGATIVE --test_trg POSITIVE --test_print_src NEGATIVE --output_file ../output/neg_to_pos-or-en_tr_ip-parallel.csv